version: '3'

services:
  #  MAIN SINGLE SPA APP
  single-spa:
    build:
      context: ./apps/single-spa
      dockerfile: Dockerfile
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.single-spa.rule=PathPrefix(`/`)'
      - 'traefik.http.services.single-spa.loadbalancer.server.port=9000'
    depends_on:
      - reverse-proxy

  
  root-angular:
    build:
      context: ./apps/root-angular
      dockerfile: Dockerfile
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.root-angular.rule=Path(`/root-angular.js`)'
      - 'traefik.http.services.root-angular.loadbalancer.server.port=7001'
    depends_on:
      - reverse-proxy

 
  # TRAEFIK
  reverse-proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
